# Generated by Django 2.0.3 on 2018-04-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_profile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('exit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SF + PH + AR', 'Simple Foyer Photogray Anti-Reflet'), ('DFB', 'Double Foyer Blanc'), ('Double Foyer avec Axe', 'DF + A'), ('DF + PH + AR', 'Double Foyer Photogray Anti-Reflet'), ('PB', 'Progressif Blanc'), ('P + PH + AR', 'Progressif Photogray Anti-Reflet'), ('PB + A', 'Progessif Blanc ave Axe')], max_length=25)),
                ('value', models.CharField(choices=[('N', 'Négatif'), ('P', 'Positif')], max_length=1)),
                ('addition', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lens.Product')),
            ],
        ),
        migrations.AddField(
            model_name='exit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lens.Product'),
        ),
        migrations.AddField(
            model_name='exit',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AddField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lens.Product'),
        ),
        migrations.AddField(
            model_name='entry',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
