# Generated by Django 2.0.3 on 2018-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SF + PH + AR', 'Simple Foyer Photogray Anti-Reflet'), ('DFB', 'Double Foyer Blanc'), ('Double Foyer avec Axe', 'DF + A'), ('DF + PH + AR', 'Double Foyer Photogray Anti-Reflet'), ('PB', 'Progressif Blanc'), ('P + PH + AR', 'Progressif Photogray Anti-Reflet'), ('PB + A', 'Progessif Blanc avec Axe')], max_length=25),
        ),
    ]
