# Generated by Django 2.0.3 on 2018-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0002_auto_20180414_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SF + PH + AR', 'Simple Foyer Photogray Anti-Reflet'), ('DFB', 'Double Foyer Blanc'), ('DF + A', 'Double Foyer avec Axe'), ('DF + PH + AR', 'Double Foyer Photogray Anti-Reflet'), ('PB', 'Progressif Blanc'), ('P + PH + AR', 'Progressif Photogray Anti-Reflet'), ('PB + A', 'Progessif Blanc avec Axe')], max_length=25),
        ),
    ]
