# Generated by Django 2.0.3 on 2018-04-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0005_auto_20180414_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
    ]
