# Generated by Django 2.0.3 on 2018-04-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0006_remove_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
