# Generated by Django 2.0.3 on 2018-04-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0008_auto_20180416_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Axe',
            field=models.IntegerField(default=0),
        ),
    ]
