# Generated by Django 2.0.3 on 2018-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0013_auto_20180416_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
