# Generated by Django 2.0.3 on 2018-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0016_auto_20180418_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-entry_date']},
        ),
        migrations.AlterModelOptions(
            name='exit',
            options={'ordering': ['-exit_date']},
        ),
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
